### ISSUE TITLE
Create rule for RG

### ISSUE THREAD

**Issue by Londerson** [Resize/Validation#1]

**Comment by mrbitsdcf** [comment]
Criar regras para o RG é uma tarefa ingrata. Cada UF tem pelo menos um instituto de identificação (sendo que alguns estados tem mais de um) e os números de RG são totalmente zoneados. Há RGs repetidos Brasil afora. Eu tiraria essa issue.

**Comment by Londerson** [comment]
Concordo @mrbitsdcf , vamos ver o que os outros devs tem a dizer a respeito antes de fechar-mos a issue.

**Comment by raphaelduartepinheiro** [comment]
Mesmo assim acho que é válido ter uma validação, pelo menos se a numeração tem o DV certo. Ao meu ver, ter dois RGs com mesmo número em um sistema (dependendo do tamanho é claro), é dificil.

**Comment by mrbitsdcf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

On 01/05/2015 02:12 PM, Raphael M. Duarte Pinheiro wrote:
> Mesmo assim acho que é válido ter uma validação, pelo menos se a numeração tem o DV certo. Ao meu ver, ter dois RGs com mesmo
> número em um sistema (dependendo do tamanho é claro), é dificil.
> 
> — Reply to this email directly or view it on GitHub <https://github.com/Resize/Validation/issues/1#issuecomment-68730255>.
> 

Validar o dígito é matematicamente simples. É um mod11 padrãozão. Mas e os RGs que não tiverem dígito? O meu não tem, por exemplo,
e é SSP/SP.

- -- 
echo
920680245503158263821824753325972325831728150312428342077412537729420364909318736253880971145983128276953696631956862757408858710644955909208239222408534030331747172248238293509539472164571738870818862971439246497991147436431430964603600458631758354381402352368220521740203494788796697543569807851284795072334480481413675418412856581412376640379241258356436205061541557366641602992820546646995466P
| dc

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iQEcBAEBCAAGBQJUqrsHAAoJEG7IGPwrPKWrrIMH/RmRPQV2tP6zLAWb95QckUNx
+7UP1honniYYqx0oYS4vQFT+foQJE2msHMB5lQ+O4xocreQYcOrRwp/DsJmCp1UC
VxcMfrwgSs0Fq3MdcOZ+f8f/kMEgByiAPUp8wYdMkeePVRyqBo0FOOySBLocGbTi
LjYNIgTsN4YBOWM0V9e3QSq0oqbkizqYctBL1c0Fn3X5JYCC7gbhjjuTPyhUs8Ez
JxUWAzLnY04agyanOfGwRd0J8xr96nQNHrnpNvDjKBySF7TkjVekqX8iLjDvp/49
T4nQkiU/l3QtSI+Dvs1+dhFwZgSoSzHrB2kYXfibJhLFvN63z2HaPIycTsBPTmM=
=Zr+h
-----END PGP SIGNATURE-----

**Comment by raphaelduartepinheiro** [comment]
@mrbitsdcf, pelo que sei, a identidade SSP/SP também tem dígito verificador. Sugiro dar uma olhada nesse site, acho que pode ser feito com estas regras, e também servir de base pro código. 

http://ghiorzi.org/DVnew.htm

**Comment by Londerson** [comment]
Se habilita a escrever essa regra @raphaelduartepinheiro ?

**Comment by raphaelduartepinheiro** [comment]
Blz, já irei aceitar. Aliás, não deveríamos estar falando em inglês?

**Comment by Londerson** [comment]
Sim, devería-mos, o @mrbitsdcf começou a discussão em PT e continuei, vamos nos policiar nesse sentido :)

**Comment by raphaelduartepinheiro** [comment]
I suggest close this, and open a new issue referring this. I've forked the project so I can begin.

**Comment by Londerson** [comment]
Good @raphaelduartepinheiro waiting you contribution ;) cloosing this issue
