### ISSUE TITLE
Create rule for is negative

### ISSUE THREAD

**Issue by Londerson** [Resize/Validation#12]
Is opposite of this:
https://github.com/Resize/Validation/blob/master/lib/rules/is_positive.rb

**Comment by psantos10** [comment]
since changes were made in the initial structure, the above link changed to: 

https://github.com/Resize/Validation/blob/master/lib/resize/rules/is_positive.rb

**Comment by psantos10** [comment]
@Londerson can you assign this issue to me?

**Comment by Londerson** [comment]
Tanks @psantos10 @FelipeCaue want make this issue  and this is a simple piece, i think you can get an issue more complex, what do you think?

**Comment by psantos10** [comment]
No problem for me. 

See the issue #3 ... I need more details. And you can assign the issue to me.
