### ISSUE TITLE
Get status of tests in CodeClimate

### ISSUE THREAD

**Issue by Londerson** [Resize/Validation#25]
We need get the status of tests, the actual status is unknow. Maybe need some integration with CodeClimate.
![captura de tela 2015-01-09 as 12 45 43](https://cloud.githubusercontent.com/assets/1335388/5681222/b43b1598-97fd-11e4-9e1a-9508e0ba5787.png)

**Comment by Londerson** [comment]
@psantos10 can you help with this issue?

**Comment by psantos10** [comment]
@Londerson yes I can.. Today I will send a pull request

**Comment by psantos10** [comment]
![captura de ecra 2015-01-14 as 13 53 42](https://cloud.githubusercontent.com/assets/374424/5739075/cad1b474-9bf4-11e4-8353-6f25b4d675f4.png)

**Comment by psantos10** [comment]
Para resolver este issue, preciso do Token : CODECLIMATE_REPO_TOKEN

E eu não tenho acesso à este token, por não possuir permissões de escrita no repositório.
