### ISSUE TITLE
Create rule for Date

### ISSUE THREAD

**Issue by Londerson** [Resize/Validation#3]

**Comment by psantos10** [comment]
@Londerson 

Please give more info about this rule. 

As I know, there are a lot of different format for dates. What must be considered in this rule for a date to be valid?

About the different formats, you can see this link: http://en.wikipedia.org/wiki/Date_format_by_country

[]s

**Comment by Londerson** [comment]
@psantos10 I think is a good and simple solution verify only if is a Date, something like:

Resize::Validation::validate(date: '2015-01-01') #true

And a good feature is pass formats of dates, something like: 

Resize::Validation::validate(date: '01-01-2015', format: 'd-m-Y')

Is more complex because we need change Resize::Validation::validate and Resize::Validation::validate! API for passing params format.

**Comment by psantos10** [comment]
I think that This issue can be closed now

**Comment by Londerson** [comment]
Good contribution @psantos10 Data.parse recognize different times formats.
