### ISSUE TITLE
Create rule for RG

### ISSUE THREAD

**Issue by Londerson** [Resize/Validation#33]
Old discussion in portuguese closed. https://github.com/Resize/Validation/issues/1

**Comment by raphaelduartepinheiro** [comment]
By the time, i'm not able to fetch modifications from the remote branch master. I'm getting an weird error in my GIT: 

R6016
- not enough space for thread data

Asap, I'll send the pull request.

**Comment by Londerson** [comment]
Send Pull Request

**Comment by raphaelduartepinheiro** [comment]
Sent. Btw, the error I mentioned before was resolved by restarting my system... Windows... Haha.
