### ISSUE TITLE
A gem named Validation already existis

### ISSUE THREAD

**Issue by psantos10** [Resize/Validation#8]
Looking for the Rubygems page, I was able to see that a gem named "Validation" already existis:

https://rubygems.org/gems/validation

This is not a problem?

**Comment by Londerson** [comment]
Yeah, have a lot of gems for validations. But i imagine for Resize::Validation a lot of rules, and features on top of this rules.

**Comment by psantos10** [comment]
My problem was not about the other validations gems that already exists... but the similar name.

**Comment by Londerson** [comment]
Yeah, lasts commits i changed this things, like organizing better namespaces, and gem name too. Now, we have (finally) a gem published into rubygems repositories.

https://rubygems.org/gems/resize-validation

**Comment by psantos10** [comment]
That sounds good now! (y)
